/** One plain sentence per sidebar item, shown as the app-tour step text. */

export const NAV_DESCRIPTIONS: Record<string, string> = {
  "/dashboard": "Your personal landing page — today's KPIs and a queue of pending work that needs your attention.",
  "/copilot": "A prioritized worklist that tells you which clients need attention right now and what to do next.",
  "/clients": "The master pipeline list — filter, search, and open any client's workspace to move them forward.",
  "/clients/duplicates": "Review customers who look like the same person, compare them side by side, and merge or dismiss. A merge cannot be undone.",
  "/agents": "Drafts an AI assistant prepared for you. Nothing is sent until you approve it.",
  "/calls": "Listen back to call recordings, read transcripts and review how each call was scored.",
  "/tasks": "Every to-do across your clients in one place, with due dates and one-click complete.",
  "/journeys": "Build automations — a trigger, followed by actions/conditions/waits, that run for you automatically.",
  "/reports": "Funnel, conversion, bottleneck, and RM performance analytics for the whole pipeline.",
  "/support": "Hand-offs from the support assistant waiting on a person, with their SLA clocks and each RM's load.",
  "/marketing": "What your ads cost and what they bring in: cost per lead, per approved KYC and per funded customer, by campaign. Read-only.",
  "/exceptions": "Everything needing manager intervention — SLA breaches, stuck clients, rejections, and missing next actions in one queue.",
  "/referrals": "Customers who refer friends: who signed up, who completed KYC and funded, the rewards that follow your rules, and monthly statements approved by two people. The CRM never pays anyone.",
  "/partners": "A read-only view of the referral programme: affiliates, referred users and payouts, straight from the referral API.",
  "/settings/stages": "Configure SLA targets and enable/disable steps in the onboarding pipeline.",
  "/settings/templates": "Manage approved WhatsApp/SMS message templates used for client outreach.",
  "/settings/users": "Create accounts, set roles and managers, and manage RM workload capacity.",
  "/settings/backoffice-import": "Import client, holding and transaction files from the back-office system: preview first, then import. Matches existing customers only.",
  "/settings/integrations": "Connect Freshdesk, Exotel, Clevertap, WhatsApp, SMS, and email — mock by default.",
  "/settings/account": "Your own profile details and password.",
  "/help": "Come back here any time for a full written guide to every feature.",
};
