import type { MetadataRoute } from "next";

// Makes Supportify installable (Add to Home Screen / Chrome "Install app") and is what the Android APK
// (a Trusted Web Activity built with PWABuilder) is generated from. `/` already routes every role to its
// own home, so it is the right start URL for everyone. Colours are the app's --primary and --background
// tokens converted from OKLCH; icons are generated by scripts/generate-pwa-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "Supportify",
    short_name: "Supportify",
    description: "Client onboarding & journey management for Supportify",
    start_url: "/",
    scope: "/",
    display: "standalone",
    theme_color: "#99CC00",
    background_color: "#000000",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
