-- Prepare the AuditLog chain for a least-privilege app role (scripts/db/setup-app-role.mjs).
--
-- The chain trigger updates "AuditLogChainHead". Running it as its owner (the migration role) means the
-- app role needs no write access to the head at all — it can only move forward through an AuditLog
-- insert. search_path is pinned so a SECURITY DEFINER function can't be hijacked via a lookalike object.
-- Safe to apply whether or not the app role exists yet, and safe to re-run.
--
-- No GRANT/REVOKE here: Prisma Postgres runs migrations as a "restricted superuser" that cannot grant or
-- revoke privileges (an earlier version of this migration failed in production on exactly that). PUBLIC has
-- no table privileges by default, so the REVOKEs it had were redundant anyway.
ALTER FUNCTION audit_log_chain_insert() SECURITY DEFINER SET search_path = public, pg_temp;
